language: php

cache:
  directories:
    - .phpunit
    - $HOME/.composer/cache/files

php:
  - 7.4

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: DEPENDENCY="symfony/symfony:^5"

before_install:
  - composer selfupdate
  - if [ "$DEPENDENCY" != "" ]; then composer require "${DEPENDENCY}" --dev --no-update; fi;

install:
  - composer update --prefer-source --no-interaction

script: composer run-script test
